name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate isometric commit calendar (full year, incl. private)
        uses: lowlighter/metrics@latest
        with:
          user: Uonlra
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          filename: metrics-isocalendar.svg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
