name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 或换成 secrets.METRICS_TOKEN
          user: Uonlra
          template: classic
          filename: metrics-isocalendar.svg

          # 启用 Isometric commit calendar 插件
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
